name = "demon slayer minecraft"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6242c406923704878f0aea59c3dfc142ce187d35c31aaf25f8f115b4a3919c5"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
