name = "demon slayer minecraft"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5de542fcd567e4377715a1fefddfa350b40d16646ed121e5b25f94c16e33eed"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
